import { Link } from "react-router-dom";
import { ArrowRight, ArrowUpRight, Bot, Check, FileText, GitBranch, MessageSquare, Sparkles } from "lucide-react";
import { BrandOrb } from "@/components/AIBackdrop";
import { GuestLink } from "@/components/GuestAuth";

export function LandingPage() {
  return <div className="landing-modern">
    <header className="landing-nav"><Link to="/" className="flex items-center gap-2.5 font-display text-xl font-bold"><BrandOrb compact />suvyon<span className="brand-tag hidden sm:inline">WORKSPACE</span></Link><nav className="flex items-center gap-3"><a href="#possibilities" className="hidden text-sm text-slate-300 sm:block">Explore</a><Link to="/login" className="px-3 py-2 text-sm font-semibold">Sign in</Link><GuestLink to="/register" className="landing-cta">Get started<ArrowUpRight size={16}/></GuestLink></nav></header>
    <main><section className="landing-hero">
      <div><div className="landing-eyebrow"><span/>YOUR IDEAS HAVE PLACES TO GO</div><h1>Think bigger.<br/>Make it <em>happen.</em></h1><p className="landing-intro">A home for your curious mind. Bring AI conversations, capable agents, and your knowledge together. Turn the next “what if” into something real.</p><div className="mt-7 flex flex-wrap items-center gap-4"><GuestLink to="/register" className="landing-cta landing-cta-large">Create your workspace<ArrowRight size={18}/></GuestLink><a href="#possibilities" className="text-sm font-semibold text-slate-300">Take a look ↓</a></div><p className="mt-5 text-xs text-slate-400">Your conversations. Your context. Your direction.</p></div>
      <div className="landing-preview"><div className="flex items-center justify-between border-b border-slate-200 pb-4"><div className="flex items-center gap-2"><BrandOrb compact/><span className="text-sm font-bold">The next big idea</span></div><span className="text-[10px] font-semibold uppercase tracking-widest text-slate-500">Example</span></div><div className="preview-tabs"><span><MessageSquare size={13}/>Chat</span><span><Bot size={13}/>Agents</span><span><FileText size={13}/>Knowledge</span></div><div className="preview-question">Help me turn my research into a launch plan.<ArrowUpRight size={18}/></div><div className="flex items-center gap-2 text-sm font-bold"><Sparkles size={17} className="text-indigo-600"/>Let's connect the dots.</div><p className="mt-3 text-sm leading-relaxed text-slate-500">Start with the audience, find the strongest opportunity, then build a plan you can act on.</p><div className="preview-steps">{["Explore your project knowledge", "Compare the possibilities", "Shape your next steps"].map((text, i) => <div key={text}><span>{i === 2 ? "03" : <Check size={14}/>}</span>{text}</div>)}</div><div className="preview-note"><GitBranch size={19}/><div><strong>One idea. More possibilities.</strong><p>Branch a conversation. Explore another angle.</p></div><ArrowUpRight size={16}/></div></div>
    </section><section id="possibilities" className="landing-features"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="landing-eyebrow">LESS JUGGLING. MORE DOING.</p><h2>Everything your next move needs.</h2></div><span className="text-sm text-slate-400">One connected workspace.</span></div><div className="landing-feature-grid">{[{icon:MessageSquare,n:"01",title:"Follow your curiosity",text:"Switch models, explore parallel conversations, and keep your thinking together."},{icon:Bot,n:"02",title:"Give your ideas a team",text:"Create agents with focused instructions and tools. Follow their progress as they work."},{icon:FileText,n:"03",title:"Build on what you know",text:"Bring your documents and project context into the conversation, with sources you can revisit."}].map(({icon:Icon,n,title,text})=><article key={n}><div className="flex items-center justify-between"><Icon size={23}/><span>{n}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div></section></main><footer className="landing-footer"><span>© {new Date().getFullYear()} Suvyon</span><span>Make room for what's next.</span><Link to="/login">Open your workspace ↗</Link></footer>
  </div>;
}
